### ISSUE TITLE
Error: Component(...): Nothing was returned from render?

### ISSUE THREAD

**Issue by PrimozRome** [sozonome/nextarter-chakra#61] opened 2022-01-21 14:42 UTC
I am using this starter template but without typescript. I have a problem in the `_document.js` file. I just transformed your  `_document.js` code into normal javascript, but Next.js is throwing the error: 

**error - Error: Component(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.**

Do you maybe know what is wrong? Below is my `_document.js` code. It is identical to yours, just removed typescript. If I remove `_document.js` then the app renders normally.

```
import createEmotionServer from "@emotion/server/create-instance";
import createEmotionCache from "/styles/emotionCache";
import Document, {
  Html,
  Head,
  Main,
  NextScript,
} from "next/document";
import * as React from "react";

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const originalRenderPage = ctx.renderPage;
    const cache = createEmotionCache();
    const { extractCriticalToChunks } = createEmotionServer(cache);

    ctx.renderPage = () =>
      originalRenderPage({
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        enhanceApp: (App) => {
          return (props) => {
            <App emotionCache={cache} {...props} />;
          }
        },
      });

    const initialProps = await Document.getInitialProps(ctx);
    const emotionStyles = extractCriticalToChunks(initialProps.html);
    const emotionStyleTags = emotionStyles.styles.map((style) => (
      <style
        data-emotion={`${style.key} ${style.ids.join(" ")}`}
        key={style.key}
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: style.css }}
      />
    ));

    return {
      ...initialProps,
      styles: [
        ...React.Children.toArray(initialProps.styles),
        ...emotionStyleTags,
      ],
    };
  }

  render() {
    return (
      <Html lang="en">
        <Head>
          <meta name="application-name" content="Gostinska Oprema" />
          <meta name="apple-mobile-web-app-capable" content="yes" />
          <meta
            name="apple-mobile-web-app-status-bar-style"
            content="default"
          />
          <meta name="apple-mobile-web-app-title" content="Gostinska Oprema" />
          <meta name="format-detection" content="telephone=no" />
          <meta name="mobile-web-app-capable" content="yes" />
          <meta name="theme-color" content="#FFFFFF" />
          <link rel="manifest" href="/manifest.json" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;

```

**Comment by sozonome** [comment] 2022-01-21 15:51
can you include the repo? It's hard to identify the problem just from the file you included here, it can be from outside `_document.js`

**Comment by sozonome** [comment] 2022-01-21 16:22
Anyways, I was able to transform this template to js with slight modifications, you can see what I do at this branch:

https://github.com/sozonome/nextarter-chakra/tree/transform/js
https://github.com/sozonome/nextarter-chakra/commit/035ce549f4148e99b1b72c61b47789c3cf00450c

Hope this helps

**Comment by PrimozRome** [comment] 2022-01-21 19:01
Thanks a lot. It's late over here so I will work on this tomorrow. Much appreciated !

**Comment by sozonome** [comment] 2022-01-22 06:17
> Thanks a lot. It's late over here so I will work on this tomorrow. Much appreciated !

No worries, happy to help 🙏 . Let me know if its resolved and I will close this issue.

**Comment by PrimozRome** [comment] 2022-01-22 08:50
@sozonome I copied your code and is working perfectly. Thanks a lot for taking time and looking into this 🙏.

I would like to understand more what is happening here in `_document.js` with this caching. Is there a resource where I could learn what is happening here inside `_document.js` and especially for what reason?

Thanks,
Primoz

**Comment by sozonome** [comment] 2022-01-22 09:10
> @sozonome I copied your code and is working perfectly. Thanks a lot for taking time and looking into this 🙏.
> 
> I would like to understand more what is happening here in `_document.js` with this caching. Is there a resource where I could learn what is happening here inside `_document.js` and especially for what reason?
> 
> Thanks,
> Primoz

It initally caused by flash of unstyled content issue (FOUC). But I think the current next.js / chakra-ui version already tackle it (either through experimental flag or else, I'll look onto it again, maybe I will remove this _document and emotion cache workaround if its not needed anymore).

References:
- https://griko.id/blog/prevent-fouc-on-next-js-chakra-ui
- https://github.com/mui-org/material-ui/blob/master/examples/nextjs-with-typescript/pages/_document.tsx

**Closed** 2022-01-22 09:10 UTC

**Comment by PrimozRome** [comment] 2022-01-22 09:23
@sozonome understood! I will be keeping my eye on the update.
